[package]
name = "yrompion/testgame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
roactSpring = "chriscerie/roact-spring@^1.1.6"
roact = "roblox/roact@1.4.2"
roactRodux = "roblox/roact-rodux@0.3.0"
rodux = "roblox/rodux@3.0.0"
hooks = "kampfkarren/roact-hooks@0.3.0"
roduxhooks = "solarhorizon/rodux-hooks@0.3.1"
